In [94]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("radheshyamkollipara/bank-customer-churn")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\shadu\.cache\kagglehub\datasets\radheshyamkollipara\bank-customer-churn\versions\1

In [95]:
pip install kagglehub

Requirement already satisfied: kagglehub in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (26.3)
Requirement already satisfied: pyyaml in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (2.34.2)
Requirement already satisfied: tqdm in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglehub) (4.70.1)
Requirement already satisfied: protobuf in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.36.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kagglehub) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kagglehub) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kagglehub) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests->kagglehub) (2026.7.22)
Requirement already satisfied: colorama in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [96]:
import pandas as pd
import numpy as np

df = pd.read_csv('Customer-Churn-Records-Messy.csv')

In [97]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,622,15603134,Pai,656.0,Spain,Female,40.0,10.0,167878.50,1.0,0.0,1.0,151887.16,0,0,5,PLATINUM,806
1,4386,15605375,Tseng,651.0,France,Male,35.0,2.0,86911.80,1.0,1.0,0.0,174094.24,0,0,5,PLATINUM,849
2,6795,15694098,Jackson,575.0,France,Female,54.0,9.0,68332.96,1.0,1.0,1.0,144390.75,0,0,5,DIAMOND,435
3,4563,15795895,Yermakova,678.0,Germany,male,36.0,1.0,117864.85,2.0,1.0,0.0,27619.06,0,0,3,SILVER,643
4,9265,15656351,Laidley,414.0,Spain,Male,60.0,3.0,0.00,2.0,1.0,1.0,93844.82,0,0,5,DIAMOND,315
5,3133,15619407,Buckley,615.0,France,Male,39.0,4.0,133707.09,1.0,1.0,1.0,108152.75,0,0,5,PLATINUM,358
6,8711,15683522,Kennedy,678.0,Germany,Female,37.0,2.0,113383.07,1.0,1.0,1.0,135123.96,0,0,2,DIAMOND,767
7,5738,15575428,Mistry,682.0,Germany,NaN,35.0,2.0,117438.92,2.0,1.0,1.0,16910.98,0,0,5,PLATINUM,348
8,7783,15595991,Hsiung,585.0,France,male,54.0,8.0,87105.32,1.0,1.0,1.0,55346.14,0,0,2,DIAMOND,302
9,6504,15587978,Boothby,455.0,Germany,Female,37.0,6.0,170057.62,1.0,0.0,1.0,NaN,0,0,5,GOLD,932

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10150 entries, 0 to 10149
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   RowNumber           10150 non-null  int64
 1   CustomerId          10150 non-null  int64
 2   Surname             10150 non-null  str
 3   CreditScore         9899 non-null   float64
 4   Geography           9998 non-null   str
 5   Gender              10029 non-null  str
 6   Age                 9969 non-null   float64
 7   Tenure              9947 non-null   float64
 8   Balance             9798 non-null   float64
 9   NumOfProducts       10029 non-null  float64
 10  HasCrCard           10049 non-null  float64
 11  IsActiveMember      9970 non-null   float64
 12  EstimatedSalary     9846 non-null   float64
 13  Exited              10150 non-null  int64
 14  Complain            10150 non-null  int64
 15  Satisfaction Score  10150 non-null  int64
 16  Card Type           10150 non-null  str
 17  Point Earned        10150 non-null  int64
dtypes: float64(8), int64(6), str(4)
memory usage: 1.4 MB

In [99]:
#df['Age'] = df['Age'].astype('Int64')

df_copy = df.copy()

In [100]:
df['Age'] = pd.to_numeric(df['Age'],errors = 'coerce').astype('Int64')

In [101]:
df[['NumOfProducts','HasCrCard']] = df[['NumOfProducts','HasCrCard']].apply(pd.to_numeric, errors = 'coerce').astype('Int64')

In [102]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [103]:
df[df['creditscore'].isnull()]

,rownumber,customerid,surname,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,complain,satisfaction_score,card_type,point_earned
23,8570,15733460,Martin,NaN,Spain,Male,36,9.0,-1221.67,2,1,1.0,104852.60,0,0,3,DIAMOND,331
235,9035,15772337,Lawrence,NaN,Germany,Female,49,0.0,153855.52,1,1,NaN,180862.26,1,1,3,PLATINUM,965
238,5763,15756535,Chibugo,NaN,Germany,Male,39,5.0,91538.51,1,1,1.0,93783.00,0,0,3,PLATINUM,336
311,4837,15728078,Yeh,NaN,France,Male,26,10.0,126392.18,1,0,1.0,43651.49,0,0,1,GOLD,494
342,6992,15752801,Bradshaw,NaN,Germany,Male,29,9.0,125961.74,2,1,0.0,160303.08,1,1,3,DIAMOND,586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9793,4496,15657317,Allan,NaN,France,NaN,32,7.0,69423.52,1,1,0.0,107499.39,0,0,2,SILVER,666
9849,9436,15635752,Lo,NaN,Germany,Male,38,4.0,111798.06,2,1,1.0,102184.66,0,0,2,SILVER,416
9871,9147,15691323,Bianchi,NaN,Germany,Male,40,4.0,89025.88,2,1,0.0,188892.19,0,0,1,GOLD,955
9877,9720,15724321,Baresi,NaN,Germany,Female,47,9.0,128298.74,1,0,0.0,149614.17,1,1,1,SILVER,630
9969,4738,15615140,Corson,NaN,France,Male,36,6.0,111168.97,1,1,1.0,189969.91,0,0,1,DIAMOND,741

In [104]:
df['geography'] = df['geography'].str.replace('Spain ','Spain')

In [105]:
df.groupby(['geography','gender'])['age'].agg(['median','mean'])

                  median       mean
geography gender
 france   Female    37.0  39.574468
          Male      37.0  40.403846
          female    33.5       33.5
          male      42.0       42.0
France    F         35.0       35.0
          Female    37.0  38.941794
          M         36.0       36.0
          Male      37.0  38.340484
          female    33.0  36.244444
          male      36.0   37.28169
GERMANY   Female    36.0  41.263158
          Male      35.0  37.695652
Germany   F         42.0       42.0
          Female    39.0  40.433911
          Male      38.0  39.418301
          female    37.5  38.566667
          male      40.0   41.40625
Spain     F         38.0       38.0
          Female    38.0  39.120912
          M         35.0  42.666667
          Male      37.0  38.656274
          female    36.0  39.575758
          male      37.0  38.516129

In [106]:
df.groupby(['geography','gender'])['age'].median()

geography  gender
 france    Female    37.0
           Male      37.0
           female    33.5
           male      42.0
France     F         35.0
           Female    37.0
           M         36.0
           Male      37.0
           female    33.0
           male      36.0
GERMANY    Female    36.0
           Male      35.0
Germany    F         42.0
           Female    39.0
           Male      38.0
           female    37.5
           male      40.0
Spain      F         38.0
           Female    38.0
           M         35.0
           Male      37.0
           female    36.0
           male      37.0
Name: age, dtype: Float64

In [107]:
df['age'] = df['age'].astype(float)


df['age'] = df['age'].fillna(df.groupby(['geography','gender'])['age'].transform('median'))

In [108]:
df.describe()

,rownumber,customerid,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,complain,satisfaction_score,point_earned
count,10150.000000,1.015000e+04,9899.000000,10148.000000,9947.000000,9798.000000,10029.0,10049.0,9970.000000,9.846000e+03,10150.00000,10150.000000,10150.000000,10150.000000
mean,5002.165517,1.569102e+07,649.647843,38.929395,5.014879,77649.420604,1.526573,0.705045,0.515948,1.013917e+05,0.20335,0.203941,3.015862,606.673202
std,2884.578424,7.192184e+04,98.280619,10.685524,2.919728,68592.337676,0.602495,0.456045,0.499771,6.943199e+04,0.40251,0.402945,1.406194,225.988787
min,1.000000,1.556570e+07,120.000000,15.000000,-1.000000,-4874.220000,0.0,0.0,0.000000,1.158000e+01,0.00000,0.000000,1.000000,119.000000
25%,2503.250000,1.562862e+07,583.000000,32.000000,2.000000,0.000000,1.0,0.0,0.000000,5.078329e+04,0.00000,0.000000,2.000000,411.000000
50%,5003.500000,1.569086e+07,651.000000,37.000000,5.000000,97321.580000,1.0,1.0,1.000000,1.001939e+05,0.00000,0.000000,3.000000,605.000000
75%,7502.750000,1.575331e+07,717.000000,44.000000,8.000000,127736.122500,2.0,1.0,1.000000,1.495142e+05,0.00000,0.000000,4.000000,801.000000
max,10000.000000,1.581569e+07,999.000000,99.000000,15.000000,970664.810000,6.0,1.0,1.000000,1.459096e+06,1.00000,1.000000,5.000000,1000.000000

In [109]:
df['age'].median()

np.float64(37.0)

In [110]:
df = df.drop(df[df['age']<18].index)

In [111]:
df[df['age'].isna()]

,rownumber,customerid,surname,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,complain,satisfaction_score,card_type,point_earned
4608,6201,15569654,Munro,NaN,NaN,Female,NaN,3.0,51293.47,1,0,0.0,35534.68,0,0,1,PLATINUM,580
9927,1960,15780514,Fuller,707.0,NaN,Male,NaN,8.0,136678.52,1,1,0.0,54290.62,0,0,4,SILVER,842

In [112]:
df[df['geography'].isna()].T

,19,62,80,93,237,240,293,299,463,471,...,9490,9616,9666,9761,9784,9854,9927,9932,9962,10020
rownumber,511,5472,7581,1348,2129,1609,4293,8765,5340,719,...,1634,7331,2505,4466,575,7684,1960,2912,5173,7409
customerid,15568506,15623202,15781975,15668445,15605835,15801466,15800287,15618203,15733966,15696859,...,15755868,15802106,15625942,15579914,15644753,15740356,15780514,15704987,15813095,15742297
surname,Forbes,Maslov,Rees,Mai,Rice,Gray,Micco,Tien,Johnstone,Oldham,...,Farmer,Craig,McDonald,Garcia,Hung,Palmer,Fuller,Lu,Nwebube,Sinclair
creditscore,524.0,704.0,708.0,521.0,743.0,574.0,706.0,773.0,496.0,474.0,...,562.0,418.0,619.0,633.0,NaN,660.0,707.0,649.0,553.0,715.0
geography,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,Female,Female,Male,Male,Male,Female,Female,Male,Female,Male,...,Male,Male,Female,Male,Male,Male,Male,Female,Male,Male
age,31.0,39.0,34.0,37.0,37.0,39.0,46.0,51.0,55.0,45.0,...,35.0,34.0,45.0,30.0,40.0,26.0,NaN,52.0,37.0,35.0
tenure,10.0,10.0,3.0,2.0,8.0,2.0,2.0,8.0,4.0,10.0,...,7.0,8.0,0.0,2.0,3.0,4.0,8.0,8.0,2.0,2.0
balance,67238.98,102556.18,0.0,0.0,69143.91,122524.61,127660.46,116197.65,125292.53,0.0,...,0.0,155973.88,0.0,109786.82,110929.96,115021.76,136678.52,49113.75,0.0,141005.47
numofproducts,2,2,1,2,2,2,2,2,1,2,...,1,1,2,2,1,1,1,1,2,1
hascrcard,1,1,0,1,0,1,1,1,1,0,...,0,1,0,1,1,0,1,1,1,1
isactivemember,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0
estimatedsalary,161811.23,171971.25,121457.88,86372.24,105780.18,88463.63,150156.82,86701.4,31532.96,172175.9,...,48869.67,154208.96,113645.4,139712.81,NaN,162443.05,54290.62,41858.43,33877.29,60407.93
exited,0,1,1,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
complain,0,1,1,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
satisfaction_score,5,3,5,5,3,1,2,3,1,4,...,3,4,4,2,3,1,4,1,1,1
card_type,GOLD,SILVER,DIAMOND,SILVER,PLATINUM,SILVER,PLATINUM,GOLD,DIAMOND,PLATINUM,...,GOLD,GOLD,SILVER,PLATINUM,GOLD,GOLD,SILVER,SILVER,SILVER,SILVER
point_earned,685,906,552,942,785,686,334,345,726,792,...,863,777,315,778,844,573,842,673,461,674

In [113]:
df.info()

<class 'pandas.DataFrame'>
Index: 10130 entries, 0 to 10149
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rownumber           10130 non-null  int64
 1   customerid          10130 non-null  int64
 2   surname             10130 non-null  str
 3   creditscore         9879 non-null   float64
 4   geography           9978 non-null   str
 5   gender              10010 non-null  str
 6   age                 10128 non-null  float64
 7   tenure              9927 non-null   float64
 8   balance             9778 non-null   float64
 9   numofproducts       10011 non-null  Int64
 10  hascrcard           10029 non-null  Int64
 11  isactivemember      9951 non-null   float64
 12  estimatedsalary     9826 non-null   float64
 13  exited              10130 non-null  int64
 14  complain            10130 non-null  int64
 15  satisfaction_score  10130 non-null  int64
 16  card_type           10130 non-null  str
 17  point_earned        10130 non-null  int64
dtypes: Int64(2), float64(6), int64(6), str(4)
memory usage: 1.5 MB

In [114]:
df['creditscore'] = df['creditscore'].fillna(df.groupby(['gender','card_type'])['creditscore'].transform('mean'))

In [115]:
df['geography'] = df['geography'].fillna("Unknown")

In [116]:
df['tenure'] = df['tenure'].fillna(df['tenure'].median())

In [117]:
df[df['balance']==0]

,rownumber,customerid,surname,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,complain,satisfaction_score,card_type,point_earned
4,9265,15656351,Laidley,414.0,Spain,Male,60.0,3.0,0.0,2,1,1.0,93844.82,0,0,5,DIAMOND,315
11,7667,15813192,Chukwuemeka,494.0,France,Male,25.0,6.0,0.0,2,0,1.0,109988.09,0,0,1,PLATINUM,376
13,3119,15789432,Mazzanti,373.0,France,Male,33.0,6.0,0.0,2,1,0.0,184954.11,0,0,3,GOLD,268
16,2955,15775562,Shoobridge,538.0,France,Female,33.0,5.0,0.0,2,1,0.0,126962.41,0,0,3,DIAMOND,290
22,34,15659428,Maggard,520.0,Spain,Female,42.0,6.0,0.0,2,1,1.0,34410.55,0,0,2,SILVER,922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10141,5579,15726313,Napolitani,687.0,Spain,Female,50.0,5.0,0.0,2,1,0.0,110230.40,0,0,1,PLATINUM,878
10143,467,15663252,Olisanugo,850.0,Spain,Female,32.0,9.0,0.0,2,1,1.0,18924.92,0,0,4,DIAMOND,765
10144,6266,15624471,Chikwado,850.0,France,Male,37.0,6.0,0.0,2,1,0.0,109291.22,0,0,1,DIAMOND,740
10146,5192,15681075,Chukwualuka,682.0,France,Female,58.0,1.0,0.0,1,1,1.0,706.50,0,0,4,PLATINUM,709
10147,5391,15573851,Macrossan,735.0,France,Female,38.0,1.0,0.0,3,0,0.0,92220.12,1,1,5,SILVER,678

In [118]:
df[df['balance'].isna()][['geography', 'age', 'tenure', 'numofproducts', 'exited']]

      geography   age  tenure  numofproducts  exited
37      Germany  57.0     4.0              1       1
81       France  38.0     7.0              2       0
187      France  35.0     5.0              1       0
244     Germany  41.0     6.0              2       0
295      France  46.0     1.0              4       1
...         ...   ...     ...            ...     ...
10075   france   33.0     6.0              2       0
10076     Spain  24.0     6.0              1       0
10098   france   37.0     7.0              1       0
10106    France  29.0     2.0              1       0
10142    France  44.0     6.0              2       0

[352 rows x 5 columns]

In [119]:
df['balance_missing'] = df['balance'].isna()

In [120]:
df.groupby('balance_missing')['exited'].mean()

balance_missing
False    0.203314
True     0.207386
Name: exited, dtype: float64

In [121]:
df.groupby('balance_missing')['age'].mean()

balance_missing
False    39.004450
True     38.133523
Name: age, dtype: float64

In [122]:
df.groupby('balance_missing')['tenure'].mean()

balance_missing
False    5.020761
True     4.872159
Name: tenure, dtype: float64

In [123]:
df.groupby('balance_missing')['estimatedsalary'].mean()

balance_missing
False    101214.719289
True     105118.542878
Name: estimatedsalary, dtype: float64

In [124]:
pd.crosstab(df['balance_missing'], df['geography'])

geography         france   France  GERMANY  Germany  Spain  Unknown
balance_missing
False                 100    4728       41     2374   2389      146
True                    6     167        2       89     82        6

In [125]:
pd.crosstab(df['balance_missing'], df['numofproducts'])

numofproducts     0     1     2    3   4  5  6
balance_missing
False            35  4904  4400  255  58  7  5
True              3   180   155    8   1  0  0

In [126]:
df[df['balance'].isna()][
    ['geography', 'age', 'tenure', 'numofproducts',
     'hascrcard', 'isactivemember', 'estimatedsalary',
     'exited', 'card_type']
].describe(include='all')

,geography,age,tenure,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,card_type
count,352,352.000000,352.000000,347.0,345.0,346.000000,3.370000e+02,352.000000,352
unique,6,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,4
top,France,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,GOLD
freq,167,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,97
mean,NaN,38.133523,4.872159,1.492795,0.730435,0.517341,1.051185e+05,0.207386,NaN
std,NaN,11.040295,2.986793,0.575843,0.444378,0.500423,9.336666e+04,0.406012,NaN
min,NaN,19.000000,0.000000,0.0,0.0,0.000000,9.007000e+01,0.000000,NaN
25%,NaN,31.000000,2.000000,1.0,0.0,0.000000,5.371828e+04,0.000000,NaN
50%,NaN,36.500000,5.000000,1.0,1.0,1.000000,1.009505e+05,0.000000,NaN
75%,NaN,43.000000,7.000000,2.0,1.0,1.000000,1.499138e+05,0.000000,NaN
max,NaN,92.000000,15.000000,4.0,1.0,1.000000,1.459096e+06,1.000000,NaN

In [127]:
df[df['balance'].isna()][
    ['geography', 'age', 'tenure', 'numofproducts', 'exited']
].describe(include='all')

       geography         age      tenure  numofproducts      exited
count        352  352.000000  352.000000          347.0  352.000000
unique         6         NaN         NaN           <NA>         NaN
top       France         NaN         NaN           <NA>         NaN
freq         167         NaN         NaN           <NA>         NaN
mean         NaN   38.133523    4.872159       1.492795    0.207386
std          NaN   11.040295    2.986793       0.575843    0.406012
min          NaN   19.000000    0.000000            0.0    0.000000
25%          NaN   31.000000    2.000000            1.0    0.000000
50%          NaN   36.500000    5.000000            1.0    0.000000
75%          NaN   43.000000    7.000000            2.0    0.000000
max          NaN   92.000000   15.000000            4.0    1.000000

In [128]:
df[df['balance'] == 0][
    ['geography', 'age', 'tenure', 'numofproducts', 'exited']
].describe(include='all')

       geography          age       tenure  numofproducts       exited
count       3506  3506.000000  3506.000000         3461.0  3506.000000
unique         4          NaN          NaN           <NA>          NaN
top       France          NaN          NaN           <NA>          NaN
freq        2256          NaN          NaN           <NA>          NaN
mean         NaN    38.515973     5.040787        1.78041     0.138905
std          NaN    10.685674     2.847386       0.515402     0.345896
min          NaN    18.000000    -1.000000            0.0     0.000000
25%          NaN    32.000000     3.000000            1.0     0.000000
50%          NaN    37.000000     5.000000            2.0     0.000000
75%          NaN    43.000000     7.000000            2.0     0.000000
max          NaN    98.000000    15.000000            6.0     1.000000

In [129]:
pd.crosstab(
    df['geography'],
    df['balance'].isna(),
    normalize='index'
) * 100

balance        False     True
geography
 france    94.339623  5.660377
France     96.588355  3.411645
GERMANY    95.348837  4.651163
Germany    96.386521  3.613479
Spain      96.681505  3.318495
Unknown    96.052632  3.947368

In [130]:
df.groupby(df['balance'].isna())[
    ['age', 'tenure', 'numofproducts', 'estimatedsalary']
].mean()

               age    tenure  numofproducts  estimatedsalary
balance
False    39.004450  5.020761       1.527939    101214.719289
True     38.133523  4.872159       1.492795    105118.542878

In [131]:
pd.crosstab(
    df['card_type'],
    df['balance'].isna(),
    normalize='index'
) * 100

balance        False     True
card_type
DIAMOND    96.497442  3.502558
GOLD       96.164492  3.835508
PLATINUM   97.232108  2.767892
SILVER     96.207033  3.792967

In [132]:
pd.crosstab(
    df['gender'],
    df['balance'].isna(),
    normalize='index'
) * 100

balance       False     True
gender
F        100.000000  0.000000
Female    96.589112  3.410888
M        100.000000  0.000000
Male      96.505073  3.494927
female    96.460177  3.539823
male      95.714286  4.285714

In [133]:
df['balance'] = df['balance'].fillna(df['balance'].median())

In [134]:
df.info()

<class 'pandas.DataFrame'>
Index: 10130 entries, 0 to 10149
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rownumber           10130 non-null  int64
 1   customerid          10130 non-null  int64
 2   surname             10130 non-null  str
 3   creditscore         10128 non-null  float64
 4   geography           10130 non-null  str
 5   gender              10010 non-null  str
 6   age                 10128 non-null  float64
 7   tenure              10130 non-null  float64
 8   balance             10130 non-null  float64
 9   numofproducts       10011 non-null  Int64
 10  hascrcard           10029 non-null  Int64
 11  isactivemember      9951 non-null   float64
 12  estimatedsalary     9826 non-null   float64
 13  exited              10130 non-null  int64
 14  complain            10130 non-null  int64
 15  satisfaction_score  10130 non-null  int64
 16  card_type           10130 non-null  str
 17  point_earned        10130 non-null  int64
 18  balance_missing     10130 non-null  bool
dtypes: Int64(2), bool(1), float64(6), int64(6), str(4)
memory usage: 1.5 MB

In [135]:
pd.crosstab(df['numofproducts'].isna(),df['gender'],normalize = 'index')*100

gender                F     Female         M       Male    female      male
numofproducts
False          0.040441  44.242240  0.040441  53.118997  1.142453  1.415428
True           0.000000  42.857143  0.000000  57.142857  0.000000  0.000000

In [136]:
df['numofproducts'].value_counts(dropna=False).sort_index()

numofproducts
0         38
1       5084
2       4555
3        263
4         59
5          7
6          5
<NA>     119
Name: count, dtype: Int64

In [137]:
df['products_missing'] = df['numofproducts'].isna()

In [138]:
df.groupby('products_missing')[
    ['age', 'tenure', 'balance', 'estimatedsalary']
].mean()

                        age    tenure       balance  estimatedsalary
products_missing
False             38.984864  5.018580  78379.864663    101308.619904
True              38.075630  4.764706  72906.005462    104666.919915

In [139]:
pd.crosstab(df['card_type'],df['products_missing'],normalize ='index')*100

products_missing      False     True
card_type
DIAMOND           98.937426  1.062574
GOLD              98.853302  1.146698
PLATINUM          98.655595  1.344405
SILVER            98.854208  1.145792

In [140]:
df['numofproducts'].value_counts(dropna=False).sort_index()

numofproducts
0         38
1       5084
2       4555
3        263
4         59
5          7
6          5
<NA>     119
Name: count, dtype: Int64

In [141]:
df.info()

<class 'pandas.DataFrame'>
Index: 10130 entries, 0 to 10149
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rownumber           10130 non-null  int64
 1   customerid          10130 non-null  int64
 2   surname             10130 non-null  str
 3   creditscore         10128 non-null  float64
 4   geography           10130 non-null  str
 5   gender              10010 non-null  str
 6   age                 10128 non-null  float64
 7   tenure              10130 non-null  float64
 8   balance             10130 non-null  float64
 9   numofproducts       10011 non-null  Int64
 10  hascrcard           10029 non-null  Int64
 11  isactivemember      9951 non-null   float64
 12  estimatedsalary     9826 non-null   float64
 13  exited              10130 non-null  int64
 14  complain            10130 non-null  int64
 15  satisfaction_score  10130 non-null  int64
 16  card_type           10130 non-null  str
 17  point_earned        10130 non-null  int64
 18  balance_missing     10130 non-null  bool
 19  products_missing    10130 non-null  bool
dtypes: Int64(2), bool(2), float64(6), int64(6), str(4)
memory usage: 1.5 MB

In [142]:
df['age'].median()

np.float64(37.0)

In [143]:
df['gender'].unique()

<StringArray>
['Female', 'Male', 'male', nan, 'female', 'F', 'M']
Length: 7, dtype: str

In [144]:
df['gender'] = df['gender'].replace(['male','M'],'Male')

In [145]:
df['gender'].value_counts(dropna=False)

gender
Male      5466
Female    4427
NaN        120
female     113
F            4
Name: count, dtype: int64

In [146]:
df.info()

<class 'pandas.DataFrame'>
Index: 10130 entries, 0 to 10149
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rownumber           10130 non-null  int64
 1   customerid          10130 non-null  int64
 2   surname             10130 non-null  str
 3   creditscore         10128 non-null  float64
 4   geography           10130 non-null  str
 5   gender              10010 non-null  str
 6   age                 10128 non-null  float64
 7   tenure              10130 non-null  float64
 8   balance             10130 non-null  float64
 9   numofproducts       10011 non-null  Int64
 10  hascrcard           10029 non-null  Int64
 11  isactivemember      9951 non-null   float64
 12  estimatedsalary     9826 non-null   float64
 13  exited              10130 non-null  int64
 14  complain            10130 non-null  int64
 15  satisfaction_score  10130 non-null  int64
 16  card_type           10130 non-null  str
 17  point_earned        10130 non-null  int64
 18  balance_missing     10130 non-null  bool
 19  products_missing    10130 non-null  bool
dtypes: Int64(2), bool(2), float64(6), int64(6), str(4)
memory usage: 1.5 MB

In [147]:
df.groupby(df['numofproducts'].isna())[['age','tenure','numofproducts','estimatedsalary']].mean()

                     age    tenure  numofproducts  estimatedsalary
numofproducts
False          38.984864  5.018580       1.526721    101308.619904
True           38.075630  4.764706           <NA>    104666.919915

In [148]:
pd.crosstab(df['geography'],
           df['numofproducts'].isna(),
        normalize = 'index')*100

numofproducts       False     True
geography
 france        100.000000  0.000000
France          98.815117  1.184883
GERMANY         97.674419  2.325581
Germany         98.741372  1.258628
Spain           98.866856  1.133144
Unknown         99.342105  0.657895

In [149]:
df['balance'] = df['balance'].fillna(df['balance'].median())

In [150]:
df['numofproducts'].value_counts(dropna=False).sort_index()

numofproducts
0         38
1       5084
2       4555
3        263
4         59
5          7
6          5
<NA>     119
Name: count, dtype: Int64

In [151]:
df[df['numofproducts'].isna()].T

,146,168,279,353,484,489,764,917,1099,1142,...,9068,9197,9234,9372,9384,9598,9813,9863,9981,9985
rownumber,8089,4227,6793,1818,9847,2166,2465,7610,448,514,...,5006,95,4034,2126,6494,9410,785,5896,3305,664
customerid,15815656,15753215,15776096,15804075,15596405,15585041,15725818,15796787,15644572,15593601,...,15741032,15676966,15569079,15777923,15723671,15591150,15571221,15704014,15676513,15788659
surname,Hopkins,Yashina,Halpern,Chuang,Udinese,Ainsworth,Chibuzo,Vassiliev,Turnbull,Isayev,...,Tsao,Capon,Hagins,Johnston,Lucciano,Nwebube,Bergamaschi,K'ung,Burns,Howells
creditscore,541.0,651.0,606.0,628.0,546.0,511.0,583.0,681.0,501.0,734.0,...,733.0,730.0,632.0,544.0,661.0,570.0,747.0,738.0,601.0,695.0
geography,Germany,Spain,Spain,Germany,Spain,France,Germany,France,France,France,...,France,Spain,Germany,France,France,Spain,Germany,Germany,Germany,France
gender,Female,Female,Male,Female,Male,Male,Male,Male,Male,Male,...,Male,Male,Male,Female,Male,Male,Male,Male,Male,Male
age,39.0,36.0,34.0,36.0,25.0,33.0,40.0,46.0,40.0,34.0,...,48.0,42.0,48.0,45.0,35.0,34.0,58.0,37.0,35.0,46.0
tenure,9.0,8.0,3.0,3.0,7.0,7.0,4.0,0.0,4.0,6.0,...,5.0,4.0,6.0,6.0,9.0,10.0,7.0,7.0,8.0,4.0
balance,100116.67,0.0,161572.24,91286.51,127728.24,0.0,107041.3,105969.42,125832.2,133598.4,...,0.0,0.0,126066.26,0.0,100107.99,0.0,116313.57,140950.92,71553.83,0.0
numofproducts,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
hascrcard,1,1,0,1,1,0,1,1,1,1,...,0,0,1,0,1,0,1,1,1,1
isactivemember,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,...,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
estimatedsalary,NaN,91652.43,191076.22,63085.94,105279.74,158313.87,5635.63,5771.56,100433.83,13107.24,...,117830.57,85982.47,64345.61,151401.33,83949.68,183387.12,190696.35,195333.98,177384.45,137537.22
exited,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
complain,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
satisfaction_score,2,3,3,4,5,4,1,4,3,4,...,1,4,3,2,3,4,3,5,4,2
card_type,GOLD,SILVER,PLATINUM,SILVER,SILVER,PLATINUM,GOLD,GOLD,DIAMOND,DIAMOND,...,DIAMOND,DIAMOND,PLATINUM,DIAMOND,GOLD,SILVER,PLATINUM,SILVER,DIAMOND,PLATINUM
point_earned,635,823,893,676,917,413,304,386,923,693,...,674,722,517,686,661,568,844,865,448,499
balance_missing,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
products_missing,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [152]:
df.groupby(df['numofproducts'].isna())[
    ['age', 'tenure', 'balance', 'estimatedsalary']
].mean()

                     age    tenure       balance  estimatedsalary
numofproducts
False          38.984864  5.018580  78379.864663    101308.619904
True           38.075630  4.764706  72906.005462    104666.919915

In [153]:
df['geography'] = df['geography'].replace('GERMANY','Germany')

In [154]:
pd.crosstab(
    df['geography'],
    df['numofproducts'].isna(),
    normalize='index'
) * 100

numofproducts       False     True
geography
 france        100.000000  0.000000
France          98.815117  1.184883
Germany         98.723065  1.276935
Spain           98.866856  1.133144
Unknown         99.342105  0.657895

In [155]:
df['geography'].unique()

<StringArray>
['Spain', 'France', 'Germany', ' france ', 'Unknown']
Length: 5, dtype: str

In [156]:
df['numofproducts'].value_counts(dropna=False).sort_index()

numofproducts
0         38
1       5084
2       4555
3        263
4         59
5          7
6          5
<NA>     119
Name: count, dtype: Int64

In [157]:
df[df['numofproducts'] == 0].T

,50,344,1040,1484,1777,2237,2311,2852,2952,3103,...,6924,7256,7486,7581,8162,8270,8356,8684,9308,9445
rownumber,5082,4348,606,764,3470,7230,2532,2923,836,5033,...,5674,2380,8352,3049,2445,9000,6781,1876,5967,6242
customerid,15757537,15645271,15814035,15622750,15656096,15635244,15752300,15705113,15575883,15750569,...,15572801,15625904,15650751,15679651,15572461,15810910,15693752,15763055,15600832,15571995
surname,Francis,Radcliffe-Brown,Lawrence,Chu,Cumbrae-Stewart,Ritchie,Sagese,P'an,Manna,Iweobiegbunam,...,Krischock,Wang,Butler,Gardiner,Kung,Royston,Reed,Onuchukwu,Moss,Harper
creditscore,610.0,615.0,601.0,742.0,679.0,716.0,607.0,685.0,559.0,684.0,...,639.0,624.0,585.0,652.044132,663.0,702.0,487.0,572.0,508.0,775.0
geography,France,Germany,France,Germany,Spain,France,Germany,Spain,France,Germany,...,Spain,France,France,Spain,Germany,Spain,France,Spain,France,Germany
gender,Female,Male,Male,Female,Female,Female,Male,Male,Male,Female,...,Male,Male,Female,Female,Female,Female,Male,Male,Female,Female
age,31.0,24.0,29.0,21.0,26.0,29.0,47.0,34.0,34.0,46.0,...,34.0,26.0,30.0,37.0,29.0,38.0,37.0,31.0,43.0,33.0
tenure,6.0,8.0,9.0,1.0,3.0,6.0,4.0,6.0,2.0,3.0,...,5.0,9.0,6.0,1.0,4.0,9.0,2.0,5.0,9.0,1.0
balance,107784.65,108528.07,0.0,114292.48,76554.06,0.0,97325.03,83264.28,137390.11,102955.14,...,97325.03,74681.9,0.0,136689.66,102714.65,97325.03,0.0,98108.79,0.0,118897.1
numofproducts,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hascrcard,1,0,1,1,1,1,1,0,1,1,...,0,0,1,1,0,1,1,0,1,1
isactivemember,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
estimatedsalary,141137.53,179488.41,80393.27,31520.4,184800.27,98998.61,79450.61,9663.28,9677.0,154137.33,...,33950.08,31231.35,137757.69,197890.65,21170.81,158527.45,126722.57,119996.95,103726.71,26362.4
exited,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
complain,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
satisfaction_score,4,2,5,2,5,2,5,5,4,2,...,2,4,5,1,4,2,5,1,3,2
card_type,PLATINUM,DIAMOND,GOLD,GOLD,GOLD,DIAMOND,GOLD,GOLD,PLATINUM,PLATINUM,...,DIAMOND,PLATINUM,PLATINUM,GOLD,PLATINUM,SILVER,SILVER,GOLD,DIAMOND,SILVER
point_earned,998,312,418,254,795,545,837,449,796,986,...,883,316,874,412,368,629,668,639,981,253
balance_missing,False,False,False,False,False,False,True,False,False,False,...,True,False,False,False,False,True,False,False,False,False
products_missing,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [158]:
df[df['numofproducts'] == 0][
    ['age', 'balance', 'hascrcard', 'isactivemember', 'exited']
]

       age    balance  hascrcard  isactivemember  exited
50    31.0  107784.65          1             1.0       0
344   24.0  108528.07          0             1.0       1
1040  29.0       0.00          1             1.0       0
1484  21.0  114292.48          1             0.0       0
1777  26.0   76554.06          1             1.0       0
2237  29.0       0.00          1             1.0       0
2311  47.0   97325.03          1             1.0       0
2852  34.0   83264.28          0             1.0       0
2952  34.0  137390.11          1             1.0       0
3103  46.0  102955.14          1             1.0       0
3436  45.0  130170.82          1             0.0       0
3711  38.0  140752.06          0             1.0       0
4156  36.0  161064.64          0             1.0       0
4288  36.0   96643.32          0             1.0       0
4491  30.0  135422.31          0             1.0       0
4690  41.0  152105.57          0             1.0       0
4788  25.0  109175.14          1             1.0       0
5388  44.0  100486.18          1             1.0       0
5477  33.0       0.00       <NA>             1.0       0
5837  23.0  163549.63          0             1.0       0
6064  31.0  139183.06          0             1.0       0
6198  32.0  102954.68          0             1.0       0
6247  46.0  107238.85          1             1.0       0
6365  33.0       0.00          1             1.0       0
6474  39.0   74896.33          0             1.0       0
6656  38.0       0.00          0             1.0       0
6748  35.0  155621.08          0             1.0       0
6866  33.0  133040.32          1             1.0       0
6924  34.0   97325.03          0             1.0       0
7256  26.0   74681.90          0             0.0       0
7486  30.0       0.00          1             1.0       0
7581  37.0  136689.66          1             0.0       0
8162  29.0  102714.65          0             1.0       0
8270  38.0   97325.03          1             1.0       0
8356  37.0       0.00          1             1.0       0
8684  31.0   98108.79          0             1.0       0
9308  43.0       0.00          1             1.0       0
9445  33.0  118897.10          1             1.0       0

In [159]:
pd.crosstab(
    df['card_type'],
    df['numofproducts'].isna(),
    normalize='index'
) * 100

numofproducts      False     True
card_type
DIAMOND        98.937426  1.062574
GOLD           98.853302  1.146698
PLATINUM       98.655595  1.344405
SILVER         98.854208  1.145792

In [160]:

df[df['numofproducts'] == 0]['hascrcard'].value_counts(dropna=False)

hascrcard
1       20
0       17
<NA>     1
Name: count, dtype: Int64

In [161]:
df[df['numofproducts'] == 0][
    ['numofproducts', 'card_type']
]

      numofproducts card_type
50                0  PLATINUM
344               0   DIAMOND
1040              0      GOLD
1484              0      GOLD
1777              0      GOLD
2237              0   DIAMOND
2311              0      GOLD
2852              0      GOLD
2952              0  PLATINUM
3103              0  PLATINUM
3436              0    SILVER
3711              0  PLATINUM
4156              0    SILVER
4288              0   DIAMOND
4491              0   DIAMOND
4690              0    SILVER
4788              0    SILVER
5388              0      GOLD
5477              0    SILVER
5837              0   DIAMOND
6064              0   DIAMOND
6198              0    SILVER
6247              0      GOLD
6365              0  PLATINUM
6474              0  PLATINUM
6656              0   DIAMOND
6748              0  PLATINUM
6866              0   DIAMOND
6924              0   DIAMOND
7256              0  PLATINUM
7486              0  PLATINUM
7581              0      GOLD
8162              0  PLATINUM
8270              0    SILVER
8356              0    SILVER
8684              0      GOLD
9308              0   DIAMOND
9445              0    SILVER

In [162]:
df[df['numofproducts'] == 0][
    ['numofproducts', 'hascrcard', 'card_type', 'balance', 'exited']
].to_string(index=False)

' numofproducts  hascrcard card_type   balance  exited\n             0          1  PLATINUM 107784.65       0\n             0          0   DIAMOND 108528.07       1\n             0          1      GOLD      0.00       0\n             0          1      GOLD 114292.48       0\n             0          1      GOLD  76554.06       0\n             0          1   DIAMOND      0.00       0\n             0          1      GOLD  97325.03       0\n             0          0      GOLD  83264.28       0\n             0          1  PLATINUM 137390.11       0\n             0          1  PLATINUM 102955.14       0\n             0          1    SILVER 130170.82       0\n             0          0  PLATINUM 140752.06       0\n             0          0    SILVER 161064.64       0\n             0          0   DIAMOND  96643.32       0\n             0          0   DIAMOND 135422.31       0\n             0          0    SILVER 152105.57       0\n             0          1    SILVER 109175.14       0\n             0          1      GOLD 100486.18       0\n             0       <NA>    SILVER      0.00       0\n             0          0   DIAMOND 163549.63       0\n             0          0   DIAMOND 139183.06       0\n             0          0    SILVER 102954.68       0\n             0          1      GOLD 107238.85       0\n             0          1  PLATINUM      0.00       0\n             0          0  PLATINUM  74896.33       0\n             0          0   DIAMOND      0.00       0\n             0          0  PLATINUM 155621.08       0\n             0          1   DIAMOND 133040.32       0\n             0          0   DIAMOND  97325.03       0\n             0          0  PLATINUM  74681.90       0\n             0          1  PLATINUM      0.00       0\n             0          1      GOLD 136689.66       0\n             0          0  PLATINUM 102714.65       0\n             0          1    SILVER  97325.03       0\n             0          1    SILVER      0.00       0\n             0          0      GOLD  98108.79       0\n             0          1   DIAMOND      0.00       0\n             0          1    SILVER 118897.10       0'

In [163]:
pd.crosstab(
    df['numofproducts'],
    df['hascrcard'],
    dropna=False
)

hascrcard      0     1     <NA>
numofproducts
0                17    20     1
1              1499  3535    50
2              1312  3199    44
3                75   183     5
4                18    40     1
5                 4     3     0
6                 1     4     0
<NA>             33    86     0

In [164]:
pd.crosstab(
    df['card_type'],
    df['numofproducts'],
    normalize = 'index'
)*100

numofproducts,0,1,2,3,4,5,6
card_type,,,,,,,
DIAMOND,0.397772,52.784407,43.237868,2.863962,0.596659,0.079554,0.039777
GOLD,0.360000,51.240000,45.400000,2.160000,0.680000,0.040000,0.120000
PLATINUM,0.400802,49.338677,46.492986,2.965932,0.641283,0.120240,0.040080
SILVER,0.359712,49.760192,46.882494,2.517986,0.439648,0.039968,0.000000

In [165]:
df['hascrcard'] = df['hascrcard'].fillna(df['hascrcard'].mode()[0])

In [166]:
df.info()

<class 'pandas.DataFrame'>
Index: 10130 entries, 0 to 10149
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rownumber           10130 non-null  int64
 1   customerid          10130 non-null  int64
 2   surname             10130 non-null  str
 3   creditscore         10128 non-null  float64
 4   geography           10130 non-null  str
 5   gender              10010 non-null  str
 6   age                 10128 non-null  float64
 7   tenure              10130 non-null  float64
 8   balance             10130 non-null  float64
 9   numofproducts       10011 non-null  Int64
 10  hascrcard           10130 non-null  Int64
 11  isactivemember      9951 non-null   float64
 12  estimatedsalary     9826 non-null   float64
 13  exited              10130 non-null  int64
 14  complain            10130 non-null  int64
 15  satisfaction_score  10130 non-null  int64
 16  card_type           10130 non-null  str
 17  point_earned        10130 non-null  int64
 18  balance_missing     10130 non-null  bool
 19  products_missing    10130 non-null  bool
dtypes: Int64(2), bool(2), float64(6), int64(6), str(4)
memory usage: 1.5 MB

In [167]:
df['numofproducts'] = df['numofproducts'].fillna(
    df['numofproducts'].mode()[0]
)

In [168]:
df['gender'] = df['gender'].fillna('Unknown')

In [169]:
df['isactivemember'] = df['isactivemember'].fillna(
    df['isactivemember'].mode()[0]
)

In [170]:
df['creditscore'] = df['creditscore'].fillna(
    df['creditscore'].median()
)

In [171]:
df['estimatedsalary'].describe()

count    9.826000e+03
mean     1.013486e+05
std      6.945787e+04
min      1.158000e+01
25%      5.077207e+04
50%      1.001456e+05
75%      1.494738e+05
max      1.459096e+06
Name: estimatedsalary, dtype: float64

In [172]:
df[df['estimatedsalary'] < 1000][
    ['customerid', 'geography', 'age', 'estimatedsalary', 'balance', 'exited']
]

       customerid geography   age  estimatedsalary    balance  exited
106      15791053   Germany  45.0            11.58  122917.71       1
136      15674678   Germany  43.0           548.52   79120.27       1
358      15809838     Spain  30.0           735.79       0.00       0
418      15634141   Germany  42.0           823.36  192390.52       0
503      15769783     Spain  37.0           807.06       0.00       0
671      15645544   Germany  30.0           582.53  129753.69       0
817      15653521   Germany  40.0           747.88  104449.80       0
958      15794413    France  32.0           878.87       0.00       0
1177     15572022    France  36.0           690.84       0.00       0
1264     15623369    France  52.0           123.07  105355.81       1
1297     15684548     Spain  38.0           417.41       0.00       1
1362     15685096    France  50.0           861.40       0.00       0
1848     15648735    France  37.0           142.81       0.00       0
1976     15788025    France  38.0           332.81       0.00       0
2158     15768233   Germany  37.0           980.93  114346.30       1
2440     15673584    France  74.0           937.15       0.00       0
2586     15569247     Spain  57.0           753.37  109679.72       0
2732     15609823     Spain  34.0           479.54  127095.14       0
2851     15792360   Unknown  32.0           777.37       0.00       0
2900     15676571    France  55.0           944.41       0.00       1
3250     15657603    France  35.0           824.00   81684.97       0
3595     15701176    France  26.0           440.20  141462.13       0
3865     15602851    France  40.0           106.67       0.00       0
4018     15681075    France  58.0           706.50       0.00       0
4201     15566211   Germany  41.0           236.45  103560.57       1
4206     15786463   Germany  59.0            91.75  121669.93       1
4284     15684198    France  38.0           216.27       0.00       0
4493     15639117     Spain  34.0           582.59       0.00       1
4588     15696605    France  49.0           523.00  180614.04       0
4692     15760988   Germany  33.0           683.37  124573.33       0
4717     15636731   Germany  36.0           447.73  101609.01       0
5255     15613048   Germany  40.0           667.66  139973.65       1
5398     15800784    France  42.0           676.06   98298.18       0
5612     15614813   Germany  46.0           487.30  107362.80       0
5644     15786237    France  28.0           823.96       0.00       0
5766     15594815    France  35.0           600.36  174790.15       0
6084     15775124     Spain  37.0           933.38       0.00       0
6471     15689526   Unknown  35.0           468.94  127543.11       1
6588     15584766    France  33.0           371.05   54503.55       0
6880     15733429   Germany  34.0           343.38  120018.86       0
7017     15640421    France  35.0           178.19       0.00       0
7207     15767818    France  55.0           978.66  132436.34       0
7318     15681550    France  41.0           598.80  121558.46       0
8202     15611669   Germany  50.0           645.61  126608.37       1
8279     15639662    France  38.0            96.27       0.00       0
8560     15607560    France  39.0           555.28   97325.03       0
8815     15747130    France  39.0           653.58       0.00       0
8885     15574858    France  37.0           287.99   97325.03       0
9079     15685243    France  63.0           502.70       0.00       0
9228     15717156    France  30.0           898.51  143396.54       0
9261     15780411    France  46.0           820.46       0.00       0
9523     15709004   Germany  22.0           961.57   93547.23       0
9539     15673020    France  49.0           738.88  204510.94       1
9593     15679693    France  31.0            90.07   97325.03       0
9740     15571816     Spain  70.0           705.18       0.00       0
9869     15764654    France  37.0           247.36   87374.88       0
10086    15757897    France  26.0           428.23  104258.80       0
10146    15681075    France  58.0           706.50       0.00       0

In [173]:
(df['estimatedsalary']<1000).sum()

np.int64(58)

In [174]:
df.nsmallest(20, 'estimatedsalary')[
    ['customerid', 'age', 'estimatedsalary', 'balance', 'exited']
]

       customerid   age  estimatedsalary    balance  exited
106      15791053  45.0            11.58  122917.71       1
9593     15679693  31.0            90.07   97325.03       0
4206     15786463  59.0            91.75  121669.93       1
8279     15639662  38.0            96.27       0.00       0
3865     15602851  40.0           106.67       0.00       0
1264     15623369  52.0           123.07  105355.81       1
1848     15648735  37.0           142.81       0.00       0
7017     15640421  35.0           178.19       0.00       0
4284     15684198  38.0           216.27       0.00       0
4201     15566211  41.0           236.45  103560.57       1
9869     15764654  37.0           247.36   87374.88       0
8885     15574858  37.0           287.99   97325.03       0
1976     15788025  38.0           332.81       0.00       0
6880     15733429  34.0           343.38  120018.86       0
6588     15584766  33.0           371.05   54503.55       0
1297     15684548  38.0           417.41       0.00       1
10086    15757897  26.0           428.23  104258.80       0
3595     15701176  26.0           440.20  141462.13       0
4717     15636731  36.0           447.73  101609.01       0
6471     15689526  35.0           468.94  127543.11       1

In [175]:
df['estimatedsalary'] = df['estimatedsalary'].fillna(df['estimatedsalary'].median())

In [176]:
# Missing values
df.isna().sum()

# Duplicate rows
df.duplicated().sum()

# Data types
df.dtypes

# Basic numeric validation
df.describe()

,rownumber,customerid,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,complain,satisfaction_score,point_earned
count,10130.000000,1.013000e+04,10130.000000,10128.00000,10130.000000,10130.000000,10130.0,10130.0,10130.00000,1.013000e+04,10130.000000,10130.000000,10130.000000,10130.000000
mean,5000.569003,1.569103e+07,649.576180,38.97418,5.015597,78315.561677,1.520533,0.707897,0.52458,1.013125e+05,0.203455,0.204047,3.015696,606.611649
std,2884.885686,7.194637e+04,97.071523,10.64833,2.889643,67493.839620,0.60179,0.454752,0.49942,6.840792e+04,0.402588,0.403024,1.406250,225.888374
min,1.000000,1.556570e+07,120.000000,18.00000,-1.000000,-4874.220000,0.0,0.0,0.00000,1.158000e+01,0.000000,0.000000,1.000000,119.000000
25%,2500.250000,1.562856e+07,585.000000,32.00000,3.000000,0.000000,1.0,0.0,0.00000,5.233876e+04,0.000000,0.000000,2.000000,411.000000
50%,5002.500000,1.569081e+07,651.000000,37.00000,5.000000,97325.030000,1.0,1.0,1.00000,1.001456e+05,0.000000,0.000000,3.000000,605.000000
75%,7500.750000,1.575334e+07,715.000000,44.00000,7.000000,126673.700000,2.0,1.0,1.00000,1.478016e+05,0.000000,0.000000,4.000000,801.000000
max,10000.000000,1.581569e+07,999.000000,99.00000,15.000000,970664.810000,6.0,1.0,1.00000,1.459096e+06,1.000000,1.000000,5.000000,1000.000000

In [177]:
df[df['tenure'] < 0][
    ['customerid', 'tenure', 'geography', 'age', 'balance', 'exited']
]

      customerid  tenure geography   age    balance  exited
394     15772650    -1.0    France  55.0  136576.02       1
1388    15582519    -1.0    France  47.0  121797.09       1
1958    15792627    -1.0     Spain  33.0   84557.82       0
2922    15801316    -1.0    France  61.0   66250.71       0
3992    15760568    -1.0   Germany  38.0  142658.04       0
5105    15779529    -1.0    France  32.0       0.00       0
5788    15704284    -1.0   Germany  57.0   95295.39       1
6011    15680752    -1.0    France  49.0       0.00       1
6488    15605918    -1.0   Germany  43.0   78992.75       0
7614    15793042    -1.0    France  39.0  129669.32       0

In [178]:
df['tenure'].value_counts().sort_index()

tenure
-1.0       10
 0.0      415
 1.0     1036
 2.0     1038
 3.0      986
 4.0      976
 5.0     1196
 6.0      955
 7.0     1031
 8.0     1015
 9.0      973
 10.0     489
 15.0      10
Name: count, dtype: int64

In [179]:
df['tenure'] = df['tenure'].replace(-1, np.nan)

In [180]:
df.groupby('gender')['tenure'].mean()

gender
F          6.250000
Female     4.974005
Male       5.066496
Unknown    4.891667
female     4.805310
Name: tenure, dtype: float64

In [181]:
df.info()

<class 'pandas.DataFrame'>
Index: 10130 entries, 0 to 10149
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rownumber           10130 non-null  int64
 1   customerid          10130 non-null  int64
 2   surname             10130 non-null  str
 3   creditscore         10130 non-null  float64
 4   geography           10130 non-null  str
 5   gender              10130 non-null  str
 6   age                 10128 non-null  float64
 7   tenure              10120 non-null  float64
 8   balance             10130 non-null  float64
 9   numofproducts       10130 non-null  Int64
 10  hascrcard           10130 non-null  Int64
 11  isactivemember      10130 non-null  float64
 12  estimatedsalary     10130 non-null  float64
 13  exited              10130 non-null  int64
 14  complain            10130 non-null  int64
 15  satisfaction_score  10130 non-null  int64
 16  card_type           10130 non-null  str
 17  point_earned        10130 non-null  int64
 18  balance_missing     10130 non-null  bool
 19  products_missing    10130 non-null  bool
dtypes: Int64(2), bool(2), float64(6), int64(6), str(4)
memory usage: 1.5 MB

In [182]:
df['tenure'].median()

np.float64(5.0)

In [183]:
df.describe()

,rownumber,customerid,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,complain,satisfaction_score,point_earned
count,10130.000000,1.013000e+04,10130.000000,10128.00000,10120.000000,10130.000000,10130.0,10130.0,10130.00000,1.013000e+04,10130.000000,10130.000000,10130.000000,10130.000000
mean,5000.569003,1.569103e+07,649.576180,38.97418,5.021542,78315.561677,1.520533,0.707897,0.52458,1.013125e+05,0.203455,0.204047,3.015696,606.611649
std,2884.885686,7.194637e+04,97.071523,10.64833,2.884873,67493.839620,0.60179,0.454752,0.49942,6.840792e+04,0.402588,0.403024,1.406250,225.888374
min,1.000000,1.556570e+07,120.000000,18.00000,0.000000,-4874.220000,0.0,0.0,0.00000,1.158000e+01,0.000000,0.000000,1.000000,119.000000
25%,2500.250000,1.562856e+07,585.000000,32.00000,3.000000,0.000000,1.0,0.0,0.00000,5.233876e+04,0.000000,0.000000,2.000000,411.000000
50%,5002.500000,1.569081e+07,651.000000,37.00000,5.000000,97325.030000,1.0,1.0,1.00000,1.001456e+05,0.000000,0.000000,3.000000,605.000000
75%,7500.750000,1.575334e+07,715.000000,44.00000,7.000000,126673.700000,2.0,1.0,1.00000,1.478016e+05,0.000000,0.000000,4.000000,801.000000
max,10000.000000,1.581569e+07,999.000000,99.00000,15.000000,970664.810000,6.0,1.0,1.00000,1.459096e+06,1.000000,1.000000,5.000000,1000.000000

In [184]:
df.isna().sum()

rownumber              0
customerid             0
surname                0
creditscore            0
geography              0
gender                 0
age                    2
tenure                10
balance                0
numofproducts          0
hascrcard              0
isactivemember         0
estimatedsalary        0
exited                 0
complain               0
satisfaction_score     0
card_type              0
point_earned           0
balance_missing        0
products_missing       0
dtype: int64

In [185]:
df.duplicated().sum()

np.int64(10)

In [186]:
df.describe()

,rownumber,customerid,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,complain,satisfaction_score,point_earned
count,10130.000000,1.013000e+04,10130.000000,10128.00000,10120.000000,10130.000000,10130.0,10130.0,10130.00000,1.013000e+04,10130.000000,10130.000000,10130.000000,10130.000000
mean,5000.569003,1.569103e+07,649.576180,38.97418,5.021542,78315.561677,1.520533,0.707897,0.52458,1.013125e+05,0.203455,0.204047,3.015696,606.611649
std,2884.885686,7.194637e+04,97.071523,10.64833,2.884873,67493.839620,0.60179,0.454752,0.49942,6.840792e+04,0.402588,0.403024,1.406250,225.888374
min,1.000000,1.556570e+07,120.000000,18.00000,0.000000,-4874.220000,0.0,0.0,0.00000,1.158000e+01,0.000000,0.000000,1.000000,119.000000
25%,2500.250000,1.562856e+07,585.000000,32.00000,3.000000,0.000000,1.0,0.0,0.00000,5.233876e+04,0.000000,0.000000,2.000000,411.000000
50%,5002.500000,1.569081e+07,651.000000,37.00000,5.000000,97325.030000,1.0,1.0,1.00000,1.001456e+05,0.000000,0.000000,3.000000,605.000000
75%,7500.750000,1.575334e+07,715.000000,44.00000,7.000000,126673.700000,2.0,1.0,1.00000,1.478016e+05,0.000000,0.000000,4.000000,801.000000
max,10000.000000,1.581569e+07,999.000000,99.00000,15.000000,970664.810000,6.0,1.0,1.00000,1.459096e+06,1.000000,1.000000,5.000000,1000.000000

In [187]:
df = df.drop_duplicates()

In [188]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\shadu\AppData\Local\Programs\Python\Python314\Lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

In [189]:
import mysql.connector

conn = mysql.connector.connect(
    host = "localhost",
    user = 'root',
    password = 'Altaf123',
    database = 'bank_churn'
)

In [190]:
df.to_csv('bank_churn.csv',index=False)

In [191]:
pd.read_csv('bank_churn.csv').describe()

,rownumber,customerid,creditscore,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,exited,complain,satisfaction_score,point_earned
count,10120.000000,1.012000e+04,10120.000000,10118.000000,10110.000000,10120.000000,10120.000000,10120.000000,10120.000000,1.012000e+04,10120.000000,10120.000000,10120.000000,10120.00000
mean,5000.653656,1.569103e+07,649.569141,38.971783,5.023541,78392.948596,1.520455,0.708004,0.524704,1.013359e+05,0.203557,0.204150,3.015119,606.60504
std,2885.521467,7.194424e+04,97.070910,10.643375,2.885050,67482.242440,0.601885,0.454703,0.499414,6.840637e+04,0.402663,0.403099,1.406108,225.91095
min,1.000000,1.556570e+07,120.000000,18.000000,0.000000,-4874.220000,0.000000,0.000000,0.000000,1.158000e+01,0.000000,0.000000,1.000000,119.00000
25%,2499.750000,1.562858e+07,585.000000,32.000000,3.000000,0.000000,1.000000,0.000000,0.000000,5.236076e+04,0.000000,0.000000,2.000000,411.00000
50%,5001.500000,1.569081e+07,651.000000,37.000000,5.000000,97325.030000,1.000000,1.000000,1.000000,1.001456e+05,0.000000,0.000000,3.000000,605.00000
75%,7502.250000,1.575335e+07,715.000000,44.000000,7.000000,126688.972500,2.000000,1.000000,1.000000,1.478078e+05,0.000000,0.000000,4.000000,801.00000
max,10000.000000,1.581569e+07,999.000000,99.000000,15.000000,970664.810000,6.000000,1.000000,1.000000,1.459096e+06,1.000000,1.000000,5.000000,1000.00000

In [195]:
df.info()

<class 'pandas.DataFrame'>
Index: 10120 entries, 0 to 10149
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rownumber           10120 non-null  int64
 1   customerid          10120 non-null  int64
 2   surname             10120 non-null  str
 3   creditscore         10120 non-null  float64
 4   geography           10120 non-null  str
 5   gender              10120 non-null  str
 6   age                 10118 non-null  float64
 7   tenure              10110 non-null  float64
 8   balance             10120 non-null  float64
 9   numofproducts       10120 non-null  Int64
 10  hascrcard           10120 non-null  Int64
 11  isactivemember      10120 non-null  float64
 12  estimatedsalary     10120 non-null  float64
 13  exited              10120 non-null  int64
 14  complain            10120 non-null  int64
 15  satisfaction_score  10120 non-null  int64
 16  card_type           10120 non-null  str
 17  point_earned        10120 non-null  int64
 18  balance_missing     10120 non-null  bool
 19  products_missing    10120 non-null  bool
dtypes: Int64(2), bool(2), float64(6), int64(6), str(4)
memory usage: 1.5 MB

In [210]:
df['age'] = df['age'].fillna(df['age'].mode()[0])

In [211]:
df.info()

<class 'pandas.DataFrame'>
Index: 10120 entries, 0 to 10149
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   rownumber           10120 non-null  int64
 1   customerid          10120 non-null  int64
 2   surname             10120 non-null  str
 3   creditscore         10120 non-null  float64
 4   geography           10120 non-null  str
 5   gender              10120 non-null  str
 6   age                 10120 non-null  float64
 7   tenure              10110 non-null  float64
 8   balance             10120 non-null  float64
 9   numofproducts       10120 non-null  Int64
 10  hascrcard           10120 non-null  Int64
 11  isactivemember      10120 non-null  float64
 12  estimatedsalary     10120 non-null  float64
 13  exited              10120 non-null  int64
 14  complain            10120 non-null  int64
 15  satisfaction_score  10120 non-null  int64
 16  card_type           10120 non-null  str
 17  point_earned        10120 non-null  int64
 18  balance_missing     10120 non-null  bool
 19  products_missing    10120 non-null  bool
dtypes: Int64(2), bool(2), float64(6), int64(6), str(4)
memory usage: 1.5 MB

In [212]:
df[df['age'].isna()]

Empty DataFrame
Columns: [rownumber, customerid, surname, creditscore, geography, gender, age, tenure, balance, numofproducts, hascrcard, isactivemember, estimatedsalary, exited, complain, satisfaction_score, card_type, point_earned, balance_missing, products_missing]
Index: []

In [213]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Altaf123@localhost/bank_churn"
)

df.to_sql(
    "bank_churn",
    con=engine,
    if_exists="replace",
    index=False
)

10120

In [218]:
df.duplicated().sum()

np.int64(0)